In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data=dt = {
    'Movie': ['Shyam Singha Roy','Jersey','Vaaranam Aayiram','Minnale','Virumaandi','Bombay','Missing'
              ,'Theri','Coolie','Shiddat','KGF','Amaran'],
    'Hero': ['Naani',None,'Suriya','Madhavan','Missing','NA',np.nan,'Vijay','Rajini'
             ,'Sunny Kaushal','Yash','SK'],
    'Heroine':['Sai Pallavi','NA',np.nan,'Reema Sen','Missing','Manisha koriala','NA','Samantha','NA',
              'Radhika Madan','Srinidhi Shetty','Sai Pallavi'],
    'Rating':['NA',10,9.5,np.nan,'Missing',8,None,9.9,3.9,10,9.5,np.nan]
    ,'Box_Office_in_CRORE':[60,90,50,39,20,10,'Missing',100,90,100,150,120]
}
df=pd.DataFrame(data)

In [ ]:
df

,Movie,Hero,Heroine,Rating,Box_Office_in_CRORE
0,Shyam Singha Roy,Naani,Sai Pallavi,NA,60
1,Jersey,None,NA,10,90
2,Vaaranam Aayiram,Suriya,NaN,9.5,50
3,Minnale,Madhavan,Reema Sen,NaN,39
4,Virumaandi,Missing,Missing,Missing,20
5,Bombay,NA,Manisha koriala,8,10
6,Missing,NaN,NA,None,Missing
7,Theri,Vijay,Samantha,9.9,100
8,Coolie,Rajini,NA,3.9,90
9,Shiddat,Sunny Kaushal,Radhika Madan,10,100
10,KGF,Yash,Srinidhi Shetty,9.5,150
11,Amaran,SK,Sai Pallavi,NaN,120

In [ ]:
df.head()

              Movie      Hero      Heroine   Rating Box_Office_in_CRORE
0  Shyam Singha Roy     Naani  Sai Pallavi       NA                  60
1            Jersey      None           NA       10                  90
2  Vaaranam Aayiram    Suriya          NaN      9.5                  50
3           Minnale  Madhavan    Reema Sen      NaN                  39
4        Virumaandi   Missing      Missing  Missing                  20

In [ ]:
df.tail()

      Movie           Hero          Heroine Rating Box_Office_in_CRORE
7     Theri          Vijay         Samantha    9.9                 100
8    Coolie         Rajini               NA    3.9                  90
9   Shiddat  Sunny Kaushal    Radhika Madan     10                 100
10      KGF           Yash  Srinidhi Shetty    9.5                 150
11   Amaran             SK      Sai Pallavi    NaN                 120

In [ ]:
df.info

<bound method DataFrame.info of                Movie           Hero          Heroine   Rating  \
0   Shyam Singha Roy          Naani      Sai Pallavi       NA
1             Jersey           None               NA       10
2   Vaaranam Aayiram         Suriya              NaN      9.5
3            Minnale       Madhavan        Reema Sen      NaN
4         Virumaandi        Missing          Missing  Missing
5             Bombay             NA  Manisha koriala        8
6            Missing            NaN               NA     None
7              Theri          Vijay         Samantha      9.9
8             Coolie         Rajini               NA      3.9
9            Shiddat  Sunny Kaushal    Radhika Madan       10
10               KGF           Yash  Srinidhi Shetty      9.5
11            Amaran             SK      Sai Pallavi      NaN

   Box_Office_in_CRORE
0                   60
1                   90
2                   50
3                   39
4                   20
5                   10
6              Missing
7                  100
8                   90
9                  100
10                 150
11                 120  >

In [ ]:
df.index

RangeIndex(start=0, stop=12, step=1)

In [ ]:
df.columns

Index(['Movie', 'Hero', 'Heroine', 'Rating', 'Box_Office_in_CRORE'], dtype='object')

In [ ]:
df.duplicated().sum()

np.int64(0)

In [ ]:
df.describe()

                   Movie   Hero Heroine  Rating  Box_Office_in_CRORE
count                 12     10      11       9                   12
unique                12     10       8       7                   10
top     Shyam Singha Roy  Naani      NA      10                   90
freq                   1      1       3       2                    2

In [ ]:
df.shape

(12, 5)

In [ ]:
df.size

60

In [ ]:
df.isnull().sum()

Movie                  0
Hero                   2
Heroine                1
Rating                 3
Box_Office_in_CRORE    0
dtype: int64

In [ ]:
df.isna().sum()

Movie                  0
Hero                   2
Heroine                1
Rating                 3
Box_Office_in_CRORE    0
dtype: int64

In [ ]:
df.replace(['None','NA',"Missing"],np.nan)

/tmp/ipykernel_1053/1988242831.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace(['None','NA',"Missing"],np.nan)

,Movie,Hero,Heroine,Rating,Box_Office_in_CRORE
0,Shyam Singha Roy,Naani,Sai Pallavi,NaN,60.0
1,Jersey,None,NaN,10.0,90.0
2,Vaaranam Aayiram,Suriya,NaN,9.5,50.0
3,Minnale,Madhavan,Reema Sen,NaN,39.0
4,Virumaandi,NaN,NaN,NaN,20.0
5,Bombay,NaN,Manisha koriala,8.0,10.0
6,NaN,NaN,NaN,NaN,NaN
7,Theri,Vijay,Samantha,9.9,100.0
8,Coolie,Rajini,NaN,3.9,90.0
9,Shiddat,Sunny Kaushal,Radhika Madan,10.0,100.0
10,KGF,Yash,Srinidhi Shetty,9.5,150.0
11,Amaran,SK,Sai Pallavi,NaN,120.0

In [ ]:
df

,Movie,Hero,Heroine,Rating,Box_Office_in_CRORE
0,Shyam Singha Roy,Naani,Sai Pallavi,NA,60
1,Jersey,None,NA,10,90
2,Vaaranam Aayiram,Suriya,NaN,9.5,50
3,Minnale,Madhavan,Reema Sen,NaN,39
4,Virumaandi,Missing,Missing,Missing,20
5,Bombay,NA,Manisha koriala,8,10
6,Missing,NaN,NA,None,Missing
7,Theri,Vijay,Samantha,9.9,100
8,Coolie,Rajini,NA,3.9,90
9,Shiddat,Sunny Kaushal,Radhika Madan,10,100
10,KGF,Yash,Srinidhi Shetty,9.5,150
11,Amaran,SK,Sai Pallavi,NaN,120

In [ ]:
df.isnull().sum()

Movie                  0
Hero                   2
Heroine                1
Rating                 3
Box_Office_in_CRORE    0
dtype: int64

In [ ]:
dp = pd.read_csv('/content/dirty_cafe_sales.csv')

In [ ]:
dp

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,ERROR,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,UNKNOWN,UNKNOWN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,UNKNOWN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [ ]:
dp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

In [ ]:
dp.dtypes

Transaction ID      object
Item                object
Quantity            object
Price Per Unit      object
Total Spent         object
Payment Method      object
Location            object
Transaction Date    object
dtype: object

In [ ]:
dp.columns

Index(['Transaction ID', 'Item', 'Quantity', 'Price Per Unit', 'Total Spent',
       'Payment Method', 'Location', 'Transaction Date'],
      dtype='object')

In [ ]:
dp.isnull().sum()

Transaction ID         0
Item                 333
Quantity             138
Price Per Unit       179
Total Spent          173
Payment Method      2579
Location            3265
Transaction Date     159
dtype: int64

In [ ]:
dp = dp.replace(['None','ERROR','NA',"Missing",'UNKNOWN'],np.nan)

In [ ]:
dp.isnull().sum()

Transaction ID         0
Item                 969
Quantity             479
Price Per Unit       533
Total Spent          502
Payment Method      3178
Location            3961
Transaction Date     460
dtype: int64

In [ ]:
dp

,Transaction ID,Item,Quantity,Price Per Unit,Total Spent,Payment Method,Location,Transaction Date
0,TXN_1961373,Coffee,2,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2,2.0,4.0,Digital Wallet,In-store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2,2.0,4.0,NaN,NaN,2023-08-30
9996,TXN_9659401,NaN,3,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3,4.0,12.0,Cash,In-store,2023-11-07

In [ ]:
dp.isnull().sum()

Transaction ID         0
Item                 969
Quantity             479
Price Per Unit       533
Total Spent          502
Payment Method      3178
Location            3961
Transaction Date     460
dtype: int64

In [ ]:
data=dt = {
    'Movie': ['Shyam Singha Roy','Jersey','Vaaranam Aayiram','Minnale','Virumaandi','Bombay','Missing'
              ,'Theri','Coolie','Shiddat','KGF','Amaran'],
    'Hero': ['Naani',None,'Suriya','Madhavan','Missing','NA',np.nan,'Vijay','Rajini'
             ,'Sunny Kaushal','Yash','SK'],
    'Heroine':['Sai Pallavi','NA',np.nan,'Reema Sen','Missing','Manisha koriala','NA','Samantha','NA',
              'Radhika Madan','Srinidhi Shetty','Sai Pallavi'],
    'Rating':['NA',10,9.5,np.nan,'Missing',8,None,9.9,3.9,10,9.5,np.nan]
    ,'Box_Office_in_CRORE':[60,90,50,39,20,10,'Missing',100,90,100,150,120]
}
df=pd.DataFrame(data)

In [ ]:
df

,Movie,Hero,Heroine,Rating,Box_Office_in_CRORE
0,Shyam Singha Roy,Naani,Sai Pallavi,NA,60
1,Jersey,None,NA,10,90
2,Vaaranam Aayiram,Suriya,NaN,9.5,50
3,Minnale,Madhavan,Reema Sen,NaN,39
4,Virumaandi,Missing,Missing,Missing,20
5,Bombay,NA,Manisha koriala,8,10
6,Missing,NaN,NA,None,Missing
7,Theri,Vijay,Samantha,9.9,100
8,Coolie,Rajini,NA,3.9,90
9,Shiddat,Sunny Kaushal,Radhika Madan,10,100
10,KGF,Yash,Srinidhi Shetty,9.5,150
11,Amaran,SK,Sai Pallavi,NaN,120

In [ ]:
df.columns

Index(['Movie', 'Hero', 'Heroine', 'Rating', 'Box_Office_in_CRORE'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Movie                12 non-null     object
 1   Hero                 10 non-null     object
 2   Heroine              11 non-null     object
 3   Rating               9 non-null      object
 4   Box_Office_in_CRORE  12 non-null     object
dtypes: object(5)
memory usage: 612.0+ bytes

In [ ]:
df.head()

              Movie      Hero      Heroine   Rating Box_Office_in_CRORE
0  Shyam Singha Roy     Naani  Sai Pallavi       NA                  60
1            Jersey      None           NA       10                  90
2  Vaaranam Aayiram    Suriya          NaN      9.5                  50
3           Minnale  Madhavan    Reema Sen      NaN                  39
4        Virumaandi   Missing      Missing  Missing                  20

In [ ]:
df.tail()

      Movie           Hero          Heroine Rating Box_Office_in_CRORE
7     Theri          Vijay         Samantha    9.9                 100
8    Coolie         Rajini               NA    3.9                  90
9   Shiddat  Sunny Kaushal    Radhika Madan     10                 100
10      KGF           Yash  Srinidhi Shetty    9.5                 150
11   Amaran             SK      Sai Pallavi    NaN                 120

In [ ]:
df.describe(include='all')

                   Movie   Hero Heroine  Rating  Box_Office_in_CRORE
count                 12     10      11       9                   12
unique                12     10       8       7                   10
top     Shyam Singha Roy  Naani      NA      10                   90
freq                   1      1       3       2                    2

In [ ]:
df.dtypes

Movie                  object
Hero                   object
Heroine                object
Rating                 object
Box_Office_in_CRORE    object
dtype: object

In [ ]:
df.isnull().sum()

Movie                  0
Hero                   2
Heroine                1
Rating                 3
Box_Office_in_CRORE    0
dtype: int64

In [ ]:
df.replace([None,'NA',"Missing"],np.nan)

/tmp/ipykernel_681/1919302233.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df.replace([None,'NA',"Missing"],np.nan)

,Movie,Hero,Heroine,Rating,Box_Office_in_CRORE
0,Shyam Singha Roy,Naani,Sai Pallavi,NaN,60.0
1,Jersey,NaN,NaN,10.0,90.0
2,Vaaranam Aayiram,Suriya,NaN,9.5,50.0
3,Minnale,Madhavan,Reema Sen,NaN,39.0
4,Virumaandi,NaN,NaN,NaN,20.0
5,Bombay,NaN,Manisha koriala,8.0,10.0
6,NaN,NaN,NaN,NaN,NaN
7,Theri,Vijay,Samantha,9.9,100.0
8,Coolie,Rajini,NaN,3.9,90.0
9,Shiddat,Sunny Kaushal,Radhika Madan,10.0,100.0
10,KGF,Yash,Srinidhi Shetty,9.5,150.0
11,Amaran,SK,Sai Pallavi,NaN,120.0

In [ ]:
df.dtypes

Movie                  object
Hero                   object
Heroine                object
Rating                 object
Box_Office_in_CRORE    object
dtype: object

In [ ]:
df1 = df.isnull().sum()

In [ ]:
df = df.replace([None,'NA',"Missing"],np.nan)
df.isnull().sum()

Movie                  1
Hero                   4
Heroine                5
Rating                 5
Box_Office_in_CRORE    1
dtype: int64

In [ ]:
df.isnull().sum

<bound method DataFrame.sum of     Movie   Hero  Heroine  Rating  Box_Office_in_CRORE
0   False  False    False    True                False
1   False   True     True   False                False
2   False  False     True   False                False
3   False  False    False    True                False
4   False   True     True    True                False
5   False   True    False   False                False
6    True   True     True    True                 True
7   False  False    False   False                False
8   False  False     True   False                False
9   False  False    False   False                False
10  False  False    False   False                False
11  False  False    False    True                False>

Data Cleaning

In [ ]:
df, replace, fillna, dropna, howall, axis=1,string, dtypes, Subset,

In [ ]:
df = df.replace([None,'NA',"Missing"],np.nan)
df.isnull().sum()

Movie                  1
Hero                   4
Heroine                5
Rating                 5
Box_Office_in_CRORE    1
dtype: int64

In [ ]:
df

,Movie,Hero,Heroine,Rating,Box_Office_in_CRORE
0,Shyam Singha Roy,Naani,Sai Pallavi,NaN,60.0
1,Jersey,NaN,NaN,10.0,90.0
2,Vaaranam Aayiram,Suriya,NaN,9.5,50.0
3,Minnale,Madhavan,Reema Sen,NaN,39.0
4,Virumaandi,NaN,NaN,NaN,20.0
5,Bombay,NaN,Manisha koriala,8.0,10.0
6,NaN,NaN,NaN,NaN,NaN
7,Theri,Vijay,Samantha,9.9,100.0
8,Coolie,Rajini,NaN,3.9,90.0
9,Shiddat,Sunny Kaushal,Radhika Madan,10.0,100.0
10,KGF,Yash,Srinidhi Shetty,9.5,150.0
11,Amaran,SK,Sai Pallavi,NaN,120.0

In [ ]:
df.isnull().sum()

Movie                  1
Hero                   4
Heroine                5
Rating                 5
Box_Office_in_CRORE    1
dtype: int64

In [ ]:
 df.replace([None,'NA',"Missing"],np.nan)

,Movie,Hero,Heroine,Rating,Box_Office_in_CRORE
0,Shyam Singha Roy,Naani,Sai Pallavi,NaN,60.0
1,Jersey,NaN,NaN,10.0,90.0
2,Vaaranam Aayiram,Suriya,NaN,9.5,50.0
3,Minnale,Madhavan,Reema Sen,NaN,39.0
4,Virumaandi,NaN,NaN,NaN,20.0
5,Bombay,NaN,Manisha koriala,8.0,10.0
6,NaN,NaN,NaN,NaN,NaN
7,Theri,Vijay,Samantha,9.9,100.0
8,Coolie,Rajini,NaN,3.9,90.0
9,Shiddat,Sunny Kaushal,Radhika Madan,10.0,100.0
10,KGF,Yash,Srinidhi Shetty,9.5,150.0
11,Amaran,SK,Sai Pallavi,NaN,120.0

In [ ]:
df.isnull().sum()

Movie                  1
Hero                   4
Heroine                5
Rating                 5
Box_Office_in_CRORE    1
dtype: int64