<a href="https://colab.research.google.com/github/jabsolo73/Data-Processing-teachings/blob/main/Mini_Task_Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Data Cleaning**

In [7]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

**Creating DataFrame into a Dataset**

In [8]:
data=dt = {
    'Movie': ['Shyam Singha Roy','Jersey','Vaaranam Aayiram','Minnale','Virumaandi','Bombay','Missing'
              ,'Theri','Coolie','Shiddat','KGF','Amaran'],
    'Hero': ['Naani',None,'Suriya','Madhavan','Missing','NA',np.nan,'Vijay','Rajini'
             ,'Sunny Kaushal','Yash','SK'],
    'Heroine':['Sai Pallavi','NA',np.nan,'Reema Sen','Missing','Manisha koriala','NA','Samantha','NA',
              'Radhika Madan','Srinidhi Shetty','Sai Pallavi'],
    'Rating':['NA',10,9.5,np.nan,'Missing',8,None,9.9,3.9,10,9.5,np.nan]
    ,'Box_Office_in_CRORE':[60,90,50,39,20,10,'Missing',100,90,100,150,120]
}
df=pd.DataFrame(data)

In [19]:
df

,Movie,Hero,Heroine,Rating,Box_Office_in_CRORE
0,Shyam Singha Roy,Naani,Sai Pallavi,NA,60
1,Jersey,None,NA,10,90
2,Vaaranam Aayiram,Suriya,NaN,9.5,50
3,Minnale,Madhavan,Reema Sen,NaN,39
4,Virumaandi,Missing,Missing,Missing,20
5,Bombay,NA,Manisha koriala,8,10
6,Missing,NaN,NA,None,Missing
7,Theri,Vijay,Samantha,9.9,100
8,Coolie,Rajini,NA,3.9,90
9,Shiddat,Sunny Kaushal,Radhika Madan,10,100
10,KGF,Yash,Srinidhi Shetty,9.5,150
11,Amaran,SK,Sai Pallavi,NaN,120

**Printing Columns**

In [9]:
df.columns

Index(['Movie', 'Hero', 'Heroine', 'Rating', 'Box_Office_in_CRORE'], dtype='object')

**Data Types**

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Movie                12 non-null     object
 1   Hero                 10 non-null     object
 2   Heroine              11 non-null     object
 3   Rating               9 non-null      object
 4   Box_Office_in_CRORE  12 non-null     object
dtypes: object(5)
memory usage: 612.0+ bytes

**Print Top and Bottom**

In [11]:
df.head(5)

              Movie      Hero      Heroine   Rating Box_Office_in_CRORE
0  Shyam Singha Roy     Naani  Sai Pallavi       NA                  60
1            Jersey      None           NA       10                  90
2  Vaaranam Aayiram    Suriya          NaN      9.5                  50
3           Minnale  Madhavan    Reema Sen      NaN                  39
4        Virumaandi   Missing      Missing  Missing                  20

In [12]:
df.tail(5)

      Movie           Hero          Heroine Rating Box_Office_in_CRORE
7     Theri          Vijay         Samantha    9.9                 100
8    Coolie         Rajini               NA    3.9                  90
9   Shiddat  Sunny Kaushal    Radhika Madan     10                 100
10      KGF           Yash  Srinidhi Shetty    9.5                 150
11   Amaran             SK      Sai Pallavi    NaN                 120

**Range of Features and Records**

In [13]:
df.index

RangeIndex(start=0, stop=12, step=1)

In [15]:
df.size

60

In [16]:
df.shape

(12, 5)

 **NULL VALUE PRE PROCESSING**

In [17]:
df.isnull().sum()

Movie                  0
Hero                   2
Heroine                1
Rating                 3
Box_Office_in_CRORE    0
dtype: int64

In [18]:
df.isna().sum()

Movie                  0
Hero                   2
Heroine                1
Rating                 3
Box_Office_in_CRORE    0
dtype: int64

In [20]:
df = df.replace([None,'NA',"Missing"],np.nan)

In [21]:
df.isnull().sum()

Movie                  1
Hero                   4
Heroine                5
Rating                 5
Box_Office_in_CRORE    1
dtype: int64

In [22]:
df

,Movie,Hero,Heroine,Rating,Box_Office_in_CRORE
0,Shyam Singha Roy,Naani,Sai Pallavi,NaN,60.0
1,Jersey,NaN,NaN,10.0,90.0
2,Vaaranam Aayiram,Suriya,NaN,9.5,50.0
3,Minnale,Madhavan,Reema Sen,NaN,39.0
4,Virumaandi,NaN,NaN,NaN,20.0
5,Bombay,NaN,Manisha koriala,8.0,10.0
6,NaN,NaN,NaN,NaN,NaN
7,Theri,Vijay,Samantha,9.9,100.0
8,Coolie,Rajini,NaN,3.9,90.0
9,Shiddat,Sunny Kaushal,Radhika Madan,10.0,100.0
10,KGF,Yash,Srinidhi Shetty,9.5,150.0
11,Amaran,SK,Sai Pallavi,NaN,120.0

In [23]:
df.describe(include='all')

                   Movie   Hero      Heroine     Rating  Box_Office_in_CRORE
count                 11      8            7   7.000000            11.000000
unique                11      8            6        NaN                  NaN
top     Shyam Singha Roy  Naani  Sai Pallavi        NaN                  NaN
freq                   1      1            2        NaN                  NaN
mean                 NaN    NaN          NaN   8.685714            75.363636
std                  NaN    NaN          NaN   2.222183            43.294971
min                  NaN    NaN          NaN   3.900000            10.000000
25%                  NaN    NaN          NaN   8.750000            44.500000
50%                  NaN    NaN          NaN   9.500000            90.000000
75%                  NaN    NaN          NaN   9.950000           100.000000
max                  NaN    NaN          NaN  10.000000           150.000000

In [26]:
df.dtypes
#automatically changed

Movie                   object
Hero                    object
Heroine                 object
Rating                 float64
Box_Office_in_CRORE    float64
dtype: object