<a href="https://colab.research.google.com/github/jabsolo73/Data-Processing-teachings/blob/main/Mini_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import pandas as pd
import numpy as np

In [7]:
data=dt = {
    'Movie': ['Shyam Singha Roy','Jersey','Vaaranam Aayiram','Minnale','Virumaandi','Bombay','Missing'
              ,'Theri','Coolie','Shiddat','KGF','Amaran'],
    'Hero': ['Naani',None,'Suriya','Madhavan','Missing','NA',np.nan,'Vijay','Rajini'
             ,'Sunny Kaushal','Yash','SK'],
    'Heroine':['Sai Pallavi','NA',np.nan,'Reema Sen','Missing','Manisha koriala','NA','Samantha','NA',
              'Radhika Madan','Srinidhi Shetty','Sai Pallavi'],
    'Rating':['NA',10,9.5,np.nan,'Missing',8,None,9.9,3.9,10,9.5,np.nan]
    ,'Box_Office_in_CRORE':[60,90,50,39,20,10,'Missing',100,90,100,150,120]
}
df=pd.DataFrame(data)

In [8]:
df

,Movie,Hero,Heroine,Rating,Box_Office_in_CRORE
0,Shyam Singha Roy,Naani,Sai Pallavi,NA,60
1,Jersey,None,NA,10,90
2,Vaaranam Aayiram,Suriya,NaN,9.5,50
3,Minnale,Madhavan,Reema Sen,NaN,39
4,Virumaandi,Missing,Missing,Missing,20
5,Bombay,NA,Manisha koriala,8,10
6,Missing,NaN,NA,None,Missing
7,Theri,Vijay,Samantha,9.9,100
8,Coolie,Rajini,NA,3.9,90
9,Shiddat,Sunny Kaushal,Radhika Madan,10,100
10,KGF,Yash,Srinidhi Shetty,9.5,150
11,Amaran,SK,Sai Pallavi,NaN,120

In [9]:
df.head()

              Movie      Hero      Heroine   Rating Box_Office_in_CRORE
0  Shyam Singha Roy     Naani  Sai Pallavi       NA                  60
1            Jersey      None           NA       10                  90
2  Vaaranam Aayiram    Suriya          NaN      9.5                  50
3           Minnale  Madhavan    Reema Sen      NaN                  39
4        Virumaandi   Missing      Missing  Missing                  20

In [10]:
df.tail()

      Movie           Hero          Heroine Rating Box_Office_in_CRORE
7     Theri          Vijay         Samantha    9.9                 100
8    Coolie         Rajini               NA    3.9                  90
9   Shiddat  Sunny Kaushal    Radhika Madan     10                 100
10      KGF           Yash  Srinidhi Shetty    9.5                 150
11   Amaran             SK      Sai Pallavi    NaN                 120

In [11]:
df.info

<bound method DataFrame.info of                Movie           Hero          Heroine   Rating  \
0   Shyam Singha Roy          Naani      Sai Pallavi       NA
1             Jersey           None               NA       10
2   Vaaranam Aayiram         Suriya              NaN      9.5
3            Minnale       Madhavan        Reema Sen      NaN
4         Virumaandi        Missing          Missing  Missing
5             Bombay             NA  Manisha koriala        8
6            Missing            NaN               NA     None
7              Theri          Vijay         Samantha      9.9
8             Coolie         Rajini               NA      3.9
9            Shiddat  Sunny Kaushal    Radhika Madan       10
10               KGF           Yash  Srinidhi Shetty      9.5
11            Amaran             SK      Sai Pallavi      NaN

   Box_Office_in_CRORE
0                   60
1                   90
2                   50
3                   39
4                   20
5                   10
6              Missing
7                  100
8                   90
9                  100
10                 150
11                 120  >

In [15]:
df.index

RangeIndex(start=0, stop=12, step=1)

In [16]:
df.columns

Index(['Movie', 'Hero', 'Heroine', 'Rating', 'Box_Office_in_CRORE'], dtype='object')

In [17]:
df.duplicated().sum()

np.int64(0)

In [18]:
df.describe()

                   Movie   Hero Heroine  Rating  Box_Office_in_CRORE
count                 12     10      11       9                   12
unique                12     10       8       7                   10
top     Shyam Singha Roy  Naani      NA      10                   90
freq                   1      1       3       2                    2

In [19]:
df.shape

(12, 5)

In [20]:
df.size

60

In [21]:
df.isnull().sum()

Movie                  0
Hero                   2
Heroine                1
Rating                 3
Box_Office_in_CRORE    0
dtype: int64

In [22]:
df.isna().sum()

Movie                  0
Hero                   2
Heroine                1
Rating                 3
Box_Office_in_CRORE    0
dtype: int64

In [24]:
df.replace(['None','NA',"Missing"],np.nan)

,Movie,Hero,Heroine,Rating,Box_Office_in_CRORE
0,Shyam Singha Roy,Naani,Sai Pallavi,NaN,60.0
1,Jersey,None,NaN,10.0,90.0
2,Vaaranam Aayiram,Suriya,NaN,9.5,50.0
3,Minnale,Madhavan,Reema Sen,NaN,39.0
4,Virumaandi,NaN,NaN,NaN,20.0
5,Bombay,NaN,Manisha koriala,8.0,10.0
6,NaN,NaN,NaN,NaN,NaN
7,Theri,Vijay,Samantha,9.9,100.0
8,Coolie,Rajini,NaN,3.9,90.0
9,Shiddat,Sunny Kaushal,Radhika Madan,10.0,100.0
10,KGF,Yash,Srinidhi Shetty,9.5,150.0
11,Amaran,SK,Sai Pallavi,NaN,120.0

In [25]:
df

,Movie,Hero,Heroine,Rating,Box_Office_in_CRORE
0,Shyam Singha Roy,Naani,Sai Pallavi,NaN,60.0
1,Jersey,None,NaN,10.0,90.0
2,Vaaranam Aayiram,Suriya,NaN,9.5,50.0
3,Minnale,Madhavan,Reema Sen,NaN,39.0
4,Virumaandi,NaN,NaN,NaN,20.0
5,Bombay,NaN,Manisha koriala,8.0,10.0
6,NaN,NaN,NaN,NaN,NaN
7,Theri,Vijay,Samantha,9.9,100.0
8,Coolie,Rajini,NaN,3.9,90.0
9,Shiddat,Sunny Kaushal,Radhika Madan,10.0,100.0
10,KGF,Yash,Srinidhi Shetty,9.5,150.0
11,Amaran,SK,Sai Pallavi,NaN,120.0

In [26]:
df.isnull().sum()

Movie                  1
Hero                   4
Heroine                5
Rating                 5
Box_Office_in_CRORE    1
dtype: int64