<a href="https://colab.research.google.com/github/jabsolo73/Data-Processing-teachings/blob/main/Numpy_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [ ]:
df2=pd.read_csv('C:\\Users\\joelb\\Downloads\\survey_results_public.csv')

Basic View functions

In [ ]:
df2

In [ ]:
df.shape

In [ ]:
df.columns

In [ ]:
df.index

In [ ]:
df.head()

In [ ]:
df.tail()

In [ ]:
df.isnull().sum()

In [ ]:
df.info()

In [ ]:
df.info()

In [ ]:
df.duplicated

In [ ]:
df.duplicated().sum()

In [ ]:
df.dtypes

In [ ]:
pd.set_option("display.max_columns",85)

In [ ]:
df

In [ ]:
df.describe()

In [ ]:
df.describe(include='all')

Filtering and location Functions using Indexing and Keywords

In [ ]:
df.loc[0,"Age"]

In [ ]:
df.loc[[1,2,3,4,5,6],["Age", "Hobbyist"]]

In [ ]:
df.iloc[0:10,0:10]

In [ ]:
df.iloc[-9:-1,-9:-1]

In [ ]:
df.iloc[[0,10],[2,50,80]]

In [ ]:
df.loc[[0,10],["Age","Gender"]]

In [ ]:
df.loc[10:1:-1,"Age":"Gender"]

In [ ]:
df.loc[1:10,"Age":"SurveyEase"]

In [ ]:
df.iloc[-10:-1,-10:-1]

In [ ]:
df.iloc[-10:-1,-86:-60]

Revision using small dataset Task

In [ ]:
df = pd.read_csv("C:\\Users\\joelb\\Downloads\\dirty_cafe_sales.csv")

In [ ]:
df

In [ ]:
df.shape

In [ ]:
df.describe()

In [ ]:
df.duplicated().sum()

In [ ]:
df.columns

In [ ]:
df.head()

In [ ]:
df.tail()

In [ ]:
df.index

In [ ]:
df.isnull().sum()

In [ ]:
df.info()

In [ ]:
df.dtypes

In [ ]:
df.describe()
#columns are not numeric, no mean, %,
#present numeric columns have string mixed so considered as objects

In [ ]:
df

Swapping Index/User defined primary key Column Task

In [ ]:
df.set_index("Transaction ID")

In [ ]:
df

In [ ]:
df.set_index("Transaction ID", inplace=True)

In [ ]:
df

In [ ]:
df.reset_index()

In [ ]:
df

In [ ]:
df.loc['TXN_4271903']

In [ ]:
df.set_index('Item',inplace=True)

In [ ]:
df

In [ ]:
df.loc['Cookie']

Creating DataFrame using pandas and performing Task on queries

In [2]:
data = {
    "Emp_ID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace", "Helen", "Ian", "Jack"],
    "Age": [25, 30, 22, 35, 28, 40, 27, 31, 29, 26],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Sales", "Finance", "IT", "Marketing", "Sales"],
    "Salary": [45000, 60000, 52000, 75000, np.nan, 68000, 49000, 72000, 58000, 61000],
    "Experience": [2, 5, 1, 8, 3, 10, 2, 6, 4, 5],
    "City": ["Chennai", "Bangalore", "Hyderabad", "Chennai", "Mumbai",
             "Delhi", "Hyderabad", "Bangalore", "Chennai", "Mumbai"],
    "Performance": ["Good", "Excellent", "Average", "Excellent", "Good",
                    "Excellent", "Average", "Good", "Excellent", "Average"]
}
df = pd.DataFrame(data)

In [ ]:
df

In [ ]:
#1 Display all employees who belong to the IT department.
df[df["Department"]=="IT"]

In [ ]:
#2 Display all employees whose Age is greater than 30.
df[df["Age"] >30]

In [ ]:
#3 Display employees who: belong to the IT department, and have a Salary greater than 65000.
df[(df["Department"]=="IT") & (df["Salary"] > 65000)]

In [ ]:
#4 Display employees who are from Chennai or Mumbai
df[df["City"] .isin (["Chennai","Mumbai"])]

In [ ]:
#5 Find all employees whose Salary is missing (NaN).
df[df["Salary"] .notnull()]

In [ ]:
#6 Display employees whose department is either:HR, Finance. Sales
df[df["Department"] .isin (["HR","IT","Finance"])]

In [ ]:
#7 Display employees whose Experience is between 3 and 6 years (inclusive).
df[df["Experience"].between(3,6)]

In [ ]:
#8 Display employees who do not belong to the IT department
df.query("Department != 'IT'")

In [ ]:
#9 Display employees who satisfy all of the following: Performance is Excellent Salary is greater than 60000 Experience is at least 5 years
df.query("Performance == 'Excellent' and Salary > 60000 and Experience >= 5")

In [ ]:
#10 Display employees who satisfy either of these conditions: Age is less than 28 and Department is HR OR
# Salary is greater than 70000 and City is Bangalore Bonus Questions
df.query("Age < 28 or Department == 'HR' or Salary > 70000 or City == 'Banglore'")

In [ ]:
# 11 Display employees whose Name starts with the letter "A"
df[df["Name"].str.startswith("A")]

In [ ]:
#12 Display employees whose City contains the word "Chennai".
df[df["City"].str.contains("Chennai")]

In [ ]:
#13 Display employees whose Performance is not "Average".
df[df["Performance"] != 'Average']

In [ ]:
#14 Salary between 50000 and 70000, and Age less than 30.
df[df["Salary"].between(50000, 70000) & (df["Age"] < 30)]

In [ ]:
#15 belong to Finance,have Experience less than 3 years, and Performance is Average.
df.query("Department == 'Finance' and Experience < 3 and Performance == 'Average'")

In [ ]:
df.sort_values('Salary')

In [ ]:
df.sort_values('Salary', ascending=False)

In [ ]:
len(df)

Using Aggregate functions

In [ ]:
print(df['Salary'].sum())
print(df['Salary'].mean())
print(df['Salary'].min())
print(df['Salary'].max())

Using SQL related Python functions

In [ ]:
df.groupby('Department')['Salary'].mean().query('Salary > 50000')

In [ ]:
df.rename(columns={'Salary':'Salary_USD'},inplace=True)

In [ ]:
df['Annual']=df['Salary_USD']*12

In [ ]:
pd.merge(df1, df2, how='inner')

In [ ]:
pd.merge(df1, df2, how='left')

In [ ]:
pd.merge(df1, df2, how='right')

In [ ]:
pd.merge(df1, df2, how='outer')

In [ ]:
pd.concat([df1,df2])

In [ ]:
df.drop_duplicates()

In [ ]:
df1.sort_values('Salary')

In [ ]:
df1.sort_values(['Department', 'Salary'])

In [ ]:
df.groupby('Department')['Salary_USD'].mean()

Basic Null Functions

In [ ]:
#null
df.isnull()
df.notnull()
df.fillna(0)
df.dropna()

Basic String Functions

In [ ]:
print(df['Name'].str.upper())
print(df['Name'].str.lower())
print(df['Name'].str.contains('ab'))
print(df['Name'].str.split())
print(df['Name'].str.len())

Basic Date operations

In [ ]:
#date operation
df['Date'] = pd.to_datetime(df['Date'])

df['Date'].dt.year
df['Date'].dt.month
df['Date'].dt.day
df['Date'].dt.day_name()

Pivoting related Columns

In [ ]:
pd.pivot_table(
    df,
    values='Salary_USD',
    index='Department',
    aggfunc='mean'
)

Reshaping

In [ ]:
#Reshaping
pd.melt()
df.pivot()
df.stack()
df.unstack()

Using Functions on DataFrame

In [6]:
#apply function
df['Salary'].apply(lambda x: x*12)

0    540000.0
1    720000.0
2    624000.0
3    900000.0
4         NaN
5    816000.0
6    588000.0
7    864000.0
8    696000.0
9    732000.0
Name: Salary, dtype: float64

In [7]:
df['Department'].map({
    'IT': 'Technology',
    'HR': 'Human Resource'
})

0    Human Resource
1        Technology
2               NaN
3        Technology
4    Human Resource
5               NaN
6               NaN
7        Technology
8               NaN
9               NaN
Name: Department, dtype: object

Merge Types like SQL

In [ ]:
pd.merge()
pd.concat()
df.join()

Ranking Functions like SQL

In [8]:
df['rank'] = df['Salary'].rank()

In [9]:
df

,Emp_ID,Name,Age,Department,Salary,Experience,City,Performance,rank
0,101,Alice,25,HR,45000.0,2,Chennai,Good,1.0
1,102,Bob,30,IT,60000.0,5,Bangalore,Excellent,5.0
2,103,Charlie,22,Finance,52000.0,1,Hyderabad,Average,3.0
3,104,David,35,IT,75000.0,8,Chennai,Excellent,9.0
4,105,Eva,28,HR,NaN,3,Mumbai,Good,NaN
5,106,Frank,40,Sales,68000.0,10,Delhi,Excellent,7.0
6,107,Grace,27,Finance,49000.0,2,Hyderabad,Average,2.0
7,108,Helen,31,IT,72000.0,6,Bangalore,Good,8.0
8,109,Ian,29,Marketing,58000.0,4,Chennai,Excellent,4.0
9,110,Jack,26,Sales,61000.0,5,Mumbai,Average,6.0

In [10]:
df['dense'] = df['Salary'].rank(method='dense')

In [11]:
df

,Emp_ID,Name,Age,Department,Salary,Experience,City,Performance,rank,dense
0,101,Alice,25,HR,45000.0,2,Chennai,Good,1.0,1.0
1,102,Bob,30,IT,60000.0,5,Bangalore,Excellent,5.0,5.0
2,103,Charlie,22,Finance,52000.0,1,Hyderabad,Average,3.0,3.0
3,104,David,35,IT,75000.0,8,Chennai,Excellent,9.0,9.0
4,105,Eva,28,HR,NaN,3,Mumbai,Good,NaN,NaN
5,106,Frank,40,Sales,68000.0,10,Delhi,Excellent,7.0,7.0
6,107,Grace,27,Finance,49000.0,2,Hyderabad,Average,2.0,2.0
7,108,Helen,31,IT,72000.0,6,Bangalore,Good,8.0,8.0
8,109,Ian,29,Marketing,58000.0,4,Chennai,Excellent,4.0,4.0
9,110,Jack,26,Sales,61000.0,5,Mumbai,Average,6.0,6.0

Cumulative Functions

In [12]:
df['cum_sum'] = df['Salary'].cumsum()
df['cum_max'] = df['Salary'].cummax()

In [13]:
df

,Emp_ID,Name,Age,Department,Salary,Experience,City,Performance,rank,dense,cum_sum,cum_max
0,101,Alice,25,HR,45000.0,2,Chennai,Good,1.0,1.0,45000.0,45000.0
1,102,Bob,30,IT,60000.0,5,Bangalore,Excellent,5.0,5.0,105000.0,60000.0
2,103,Charlie,22,Finance,52000.0,1,Hyderabad,Average,3.0,3.0,157000.0,60000.0
3,104,David,35,IT,75000.0,8,Chennai,Excellent,9.0,9.0,232000.0,75000.0
4,105,Eva,28,HR,NaN,3,Mumbai,Good,NaN,NaN,NaN,NaN
5,106,Frank,40,Sales,68000.0,10,Delhi,Excellent,7.0,7.0,300000.0,75000.0
6,107,Grace,27,Finance,49000.0,2,Hyderabad,Average,2.0,2.0,349000.0,75000.0
7,108,Helen,31,IT,72000.0,6,Bangalore,Good,8.0,8.0,421000.0,75000.0
8,109,Ian,29,Marketing,58000.0,4,Chennai,Excellent,4.0,4.0,479000.0,75000.0
9,110,Jack,26,Sales,61000.0,5,Mumbai,Average,6.0,6.0,540000.0,75000.0

Conditional Columns

In [14]:
df['Status'] = np.where(
    df['Salary'] > 50000,
    'High',
    'Low'
)

In [15]:
df

,Emp_ID,Name,Age,Department,Salary,Experience,City,Performance,rank,dense,cum_sum,cum_max,Status
0,101,Alice,25,HR,45000.0,2,Chennai,Good,1.0,1.0,45000.0,45000.0,Low
1,102,Bob,30,IT,60000.0,5,Bangalore,Excellent,5.0,5.0,105000.0,60000.0,High
2,103,Charlie,22,Finance,52000.0,1,Hyderabad,Average,3.0,3.0,157000.0,60000.0,High
3,104,David,35,IT,75000.0,8,Chennai,Excellent,9.0,9.0,232000.0,75000.0,High
4,105,Eva,28,HR,NaN,3,Mumbai,Good,NaN,NaN,NaN,NaN,Low
5,106,Frank,40,Sales,68000.0,10,Delhi,Excellent,7.0,7.0,300000.0,75000.0,High
6,107,Grace,27,Finance,49000.0,2,Hyderabad,Average,2.0,2.0,349000.0,75000.0,Low
7,108,Helen,31,IT,72000.0,6,Bangalore,Good,8.0,8.0,421000.0,75000.0,High
8,109,Ian,29,Marketing,58000.0,4,Chennai,Excellent,4.0,4.0,479000.0,75000.0,High
9,110,Jack,26,Sales,61000.0,5,Mumbai,Average,6.0,6.0,540000.0,75000.0,High

Performance Metric Status

In [ ]:
#df.info()
#df.describe()
#df.memory_usage()
#df.shape
#df.dtypes